// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaurDanielProject.Migrations
{
    [DbContext(typeof(FaurDanielProjectContext))]
    partial class FaurDanielProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21");

            modelBuilder.Entity("FaurDanielProiectMedii.Models.Antrenor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("prenume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Antrenor");
                });

            modelBuilder.Entity("FaurDanielProiectMedii.Models.Clasa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntrenorID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntensitateID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("AntrenorID");

                    b.HasIndex("IntensitateID");

                    b.HasIndex("NivelID");

                    b.ToTable("Clasa");
                });

            modelBuilder.Entity("FaurDanielProiectMedii.Models.Intensitate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Intensitate");
                });

            modelBuilder.Entity("FaurDanielProiectMedii.Models.Nivel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Nivel");
                });

            modelBuilder.Entity("FaurDanielProiectMedii.Models.Clasa", b =>
                {
                    b.HasOne("FaurDanielProiectMedii.Models.Antrenor", "Antrenor")
                        .WithMany()
                        .HasForeignKey("AntrenorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaurDanielProiectMedii.Models.Intensitate", "Intensitate")
                        .WithMany()
                        .HasForeignKey("IntensitateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaurDanielProiectMedii.Models.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
